### ISSUE TITLE
Saving user password in encrypted form locally on the disk.

### ISSUE THREAD

**Issue by mathamonkey** [apsknight/acl#3]
Most of the students hardly remember ERP password, OAuth has eliminated the need to remember it. This will make it a lot more user-friendly. We will have a prompt asking, do you want to save password?
If the user agrees we will save it in a password protected SQLite database against user Roll number.

**Comment by apsknight** [comment]
Solved by #4 

Thanks, @MadhavChoudhary, and @mathamonkey!
